server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    default-property-inclusion: NON_NULL
management:
  security:
    enabled: false
endpoints:
  restart:
    enabled: true
redis:
  first:
    host: localhost
    port: 6379
    password: null
  second:
    host: 1.1.1.1:6379
    port: null
    enalbed: false
    password: null
task:
  fixedThreadPool:
    maxCount: 20
  full:
    dir: C:/develop/FullData
  logs:
    maxsize: 30
user:
  collections:
    INFXPG001:
      '01':
        name: MenuAll
        key: menu_stb_svc_id
      '02':
        name: MenuHome
        key: menu_stb_svc_id
      '03':
        name: MenuMonthly
        key: menu_stb_svc_id
      '04':
        name: Menu4
        key: menu_stb_svc_id
      '05':
        name: Menu5
        key: menu_stb_svc_id
      '06':
        name: Menu6
        key: menu_stb_svc_id
      '07':
        name: Menu888
        key: menu_stb_svc_id
    INFXPG030:
      '01':
        name: Contents
        key: epsd_rslu_id