spring:
  http:
    encoding:
      charset: UTF-8
server:
  port: 8080
zuul:
  routes:
    xpg-sample-ge: /ge/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
management:
  security:
    enabled: false
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    senstive: false