spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    default-property-inclusion: NON_NULL
redis:
  first:
    host: localhost
    port: 6379
    password: 
  second:
    host: 1.1.1.1:6379
    port: 
    enalbed: false
    password: 
task:
  fixedThreadPool:
    maxCount: 20
  full:
    dir: C:/develop/FullData
user:
  collections:
    INFXPG001: MenuAll
    INFXPG030: Contents
