spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    default-property-inclusion: NON_NULL
    generator:
      write-numbers-as-strings: true
  redis:
    host: localhost
    port: 6379
    password: null
management:
  security:
    enabled: false