spring:
  http:
    encoding:
      charset: UTF-8
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
    enabled: false
  instance:
    preferIpAddress: true
management:
  security:
    enabled: false
endpoints:
  restart:
    enabled: true
redis:
  first:
    host: localhost
    port: 6379
    password: null
  second:
    host: localhost
    port: 6379
    enalbed: false
    password: null
mq:
  suy:
    url: http://localhost:8080
  back:
    dir: C:\develop\logs\
task:
  fieldcheckswitch: true
  fixedThreadPool:
    maxCount: 30
  full:
    dir: C:\develop\FullData
  retry:
    dir: C:\develop\retry\
    url: http://localhost:8080/mq/test/
    ssuurl: http://localhost:8080/mq/test/
  logs:
    maxsize: 30
  partial:
    url: http://ncms-api-dev.skb-suy-dev01.mybluemix.net
    user: user
    password: user123
  my:
    host: localhost
    ip: 127.0.0.1
    errorDir: C:\errorlog
logging:
  file: C:\logs\dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: info, error
    org.springframework.amqp: error
    com.skb.xpg.nxpg: DEBUG
    org.hibernate: info, error
