spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    default-property-inclusion: NON_NULL
redis:
  first:
    host: localhost
    port: 6379
    password: null
  second:
    host: 1.1.1.1:6379
    port: null
    enalbed: false
    password: null
task:
  fixedThreadPool:
    maxCount: 20
  full:
    dir: C:/develop/FullData
user:
  collections:
    INFXPG001:
      '01': 
        name: MenuAll
        key: menu_stb_svc_id
    INFXPG030:
      '01': 
        name: Contents
        key: epsd_rslu_id